name: Lawn AI Master Scheduler

on:
  schedule:
    - cron: '* * * * *'   # every minute; your app decides what to run
  workflow_dispatch:

concurrency:
  group: master-scheduler
  cancel-in-progress: false

jobs:
  trigger-app-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cron function (require 2xx + JSON)
        env:
          CRON_URL: ${{ secrets.CRON_URL }}
          BASE44_API_KEY: ${{ secrets.BASE44_API_KEY }}   # optional if your app needs it
        run: |
          set -euo pipefail

          if [ -z "${CRON_URL:-}" ]; then
            echo "❌ CRON_URL secret is not set"
            exit 1
          fi

          echo "→ GET $CRON_URL"
          mkdir -p _resp
          HTTP=$(curl -sS -L -D _resp/h -o _resp/b -w "%{http_code}" \
                 -H "Accept: application/json" \
                 -H "User-Agent: GitHub-Actions-MasterScheduler/1.0" \
                 ${BASE44_API_KEY:+ -H "Authorization: Bearer $BASE44_API_KEY"} \
                 --max-time 30 \
                 "$CRON_URL" || echo "000")
          CT=$(grep -i '^content-type:' _resp/h || true)
          echo "HTTP $HTTP | $CT"

          if [[ "$HTTP" =~ ^2 ]] && echo "$CT" | grep -qi 'application/json'; then
            echo "✅ JSON success:"
            head -n 200 _resp/b
          else
            echo "⚠️  Not successful JSON. Body (first lines):"
            head -n 30 _resp/b || true
            echo ""
            echo "Headers (first lines):"
            head -n 20 _resp/h || true
            exit 1
          fi
