name: Lawn AI Master Scheduler

on:
  schedule:
    - cron: '* * * * *'   # every minute
  workflow_dispatch:

concurrency:
  group: master-scheduler
  cancel-in-progress: false

jobs:
  trigger-app-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cron (prefer /api, fallback /functions; require 2xx JSON)
        env:
          BASE: ${{ secrets.APP_DOMAIN }}
          AUTH: ${{ secrets.BASE44_API_KEY }}   # optional if your app requires it
        run: |
          set -euo pipefail
          BASE="${BASE%/}"
          mkdir -p _resp

          try_url () {
            URL="$1"
            echo "→ GET $URL"
            HTTP=$(curl -sS -D _resp/h -o _resp/b -w "%{http_code}" \
                   -H "Accept: application/json" \
                   -H "User-Agent: GitHub-Actions-MasterScheduler/1.0" \
                   ${AUTH:+ -H "Authorization: Bearer $AUTH"} \
                   "$URL" || echo "000")
            CT=$(grep -i '^content-type:' _resp/h || true)
            echo "HTTP $HTTP | $CT"
            if [[ "$HTTP" =~ ^2 ]] && echo "$CT" | grep -qi 'application/json'; then
              echo "✅ JSON success:"
              head -n 200 _resp/b
              return 0
            fi
            echo "⚠️  Not successful JSON; first lines of body:"
            head -n 20 _resp/b || true
            return 1
          }

          # Try likely function routes (with & without trailing slash)
          CANDIDATES=(
            "$BASE/api/cronTrigger"
            "$BASE/api/cronTrigger/"
            "$BASE/functions/cronTrigger"
            "$BASE/functions/cronTrigger/"
            "$BASE/api/cron"
            "$BASE/api/cron/"
          )

          for U in "${CANDIDATES[@]}"; do
            if try_url "$U"; then
              exit 0
            fi
          done

          echo "❌ No 2xx JSON from known routes."
          echo "Tip: Set APP_DOMAIN to the exact env Base44 updated (Preview vs App),"
          echo "     or paste the precise endpoint path from the Automation Setup page."
          exit 1
