name: Lawn AI Master Scheduler

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger-app-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Master Cron Endpoint
        run: |
          curl -X GET "${{ secrets.APP_DOMAIN }}/functions/cronTrigger" \
            -H "User-Agent: GitHub-Actions-MasterScheduler/1.0" \
            --fail --silent --show-error
