name: Debug Ping
on: { workflow_dispatch: {} }

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Validate APP_DOMAIN
        run: |
          DOMAIN="${{ secrets.APP_DOMAIN }}"
          DOMAIN="$(printf "%s" "$DOMAIN" | awk '{$1=$1};1')"
          if [ -z "$DOMAIN" ]; then echo "❌ APP_DOMAIN empty"; exit 1; fi
          case "$DOMAIN" in https://*) ;; *) echo "❌ Must start with https://"; exit 1;; esac
          echo "✅ APP_DOMAIN present (masked)."

      - name: GET root
        run: |
          BASE="${{ secrets.APP_DOMAIN }}"; BASE="${BASE%/}"
          curl -i "$BASE" || true

      - name: POST /functions/taskScheduler
        run: |
          BASE='${{ secrets.APP_DOMAIN }}'; BASE="${BASE%/}"
          curl -i -X POST "$BASE/functions/taskScheduler" \
            -H "Content-Type: application/json" \
            -d '{}' || true

      - name: POST /functions/cronTrigger
        run: |
          BASE='${{ secrets.APP_DOMAIN }}'; BASE="${BASE%/}"
          curl -i -X POST "$BASE/functions/cronTrigger" \
            -H "Content-Type: application/json" \
            -d '{}' || true
