name: Task Scheduler (Reports + Tests)

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  check-scheduled-tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: task-scheduler
      cancel-in-progress: true
    steps:
      - name: Ping fiveMinuteScheduler
        run: |
          curl -X GET "${{ secrets.APP_DOMAIN }}/functions/fiveMinuteScheduler" \
            -H "User-Agent: GitHub-Actions-TaskScheduler/1.0" \
            -H "X-Cron-Token: ${{ secrets.CRON_TOKEN }}" \
            --fail --silent --show-error --max-time 20 --retry 3 --retry-all-errors
