name: Task Scheduler (Daily Tests)

on:
  schedule:
    - cron: '* * * * *'   # every minute
  workflow_dispatch:

jobs:
  check-scheduled-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: GET /functions/taskScheduler
        run: |
          set -e
          BASE="${{ secrets.APP_DOMAIN }}"
          BASE="${BASE%/}"  # strip trailing slash
          echo "GET $BASE/functions/taskScheduler"
          curl -i -X GET "$BASE/functions/taskScheduler" \
            -H "User-Agent: GitHub-Actions-TaskScheduler/1.0" \
            --silent --show-error --fail
          echo "✅ taskScheduler responded"
