name: Task Scheduler (Daily Tests)

on:
  schedule:
    - cron: '* * * * *'   # every minute
  workflow_dispatch:

jobs:
  check-scheduled-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: POST /functions/taskScheduler
        run: |
          set -e
          BASE="${{ secrets.APP_DOMAIN }}"
          # strip trailing slash to avoid double //functions
          BASE="${BASE%/}"
          echo "POST $BASE/functions/taskScheduler"
          curl -i -X POST "$BASE/functions/taskScheduler" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-TaskScheduler/1.0" \
            -d '{}' \
            --silent --show-error --fail
          echo "✅ taskScheduler responded"
