name: Weather Logger (4x Daily)

on:
  schedule:
    - cron: '0 12,18,22 * * *'
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  log-weather:
    runs-on: ubuntu-latest
    steps:
      - name: GET /functions/cronTrigger
        run: |
          set -e
          BASE="${{ secrets.APP_DOMAIN }}"
          BASE="${BASE%/}"
          echo "GET $BASE/functions/cronTrigger"
          curl -i -X GET "$BASE/functions/cronTrigger" \
            -H "User-Agent: GitHub-Actions-WeatherLogger/1.0" \
            --silent --show-error --fail
          echo "✅ cronTrigger responded"
